gen-schedules: check for alliance length in function

diff --git a/gen-schedules b/gen-schedules
--- a/gen-schedules
+++ b/gen-schedules
@@ -14,13 +14,20 @@ schedule_it() {
     # $1 = rounds
     # $2 = alliance size
     # $3 = team count
-    echo "making schedule '${3}_${2}v${2}.txt'..."
 
-    MatchMaker -a "$2" -r "$1" -t "$3" -b > "${3}_${2}v${2}.txt"
+    if [[ $1 <= $(($2 * 2)) ]]; then
+        echo "making schedule '${3}_${2}v${2}.txt'..."
 
-    awk -f "$AWK_STRIPPER" "${3}_${2}v${2}.txt"
+        MatchMaker -a "$2" -r "$1" -t "$3" -b > "${3}_${2}v${2}.txt"
 
-    mv "${3}_${2}v${2}.csv" ../out
+        awk -f "$AWK_STRIPPER" "${3}_${2}v${2}.txt"
+
+        mv "${3}_${2}v${2}.csv" ../out
+    else
+        echo "Cannot generate a schedule with $3 ships with alliance length $2!"
+        
+        exit 1
+    fi
 }
 
 export -f schedule_it
@@ -55,7 +62,6 @@ for i in 2 3 4; do
 
     cd "./${DIRNAME}"
     
-    parallel schedule_it {1} {2} {3} ::: $1 ::: $(seq 2 4) ::: $(seq 1 100)
 
     # for j in $(seq $(expr "$i" '*' '2') $2); do
 
@@ -70,5 +76,5 @@ for i in 2 3 4; do
     
     cd ..
 done
+parallel schedule_it {1} {2} {3} ::: $1 ::: $(seq 2 4) ::: $(seq 1 100)
 
-wait
